name = "LocallyPurifiedDensityOperators"
uuid = "b344c096-2e8c-4725-a780-ea846911edde"
version = "0.1.0"
authors = ["Davide Ferracin <davide.ferracin@protonmail.com>"]

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
